name: airliner
services:
  web:
    container_name: airliner_web
    build:
      context: .
      # pipe symbol op volgende regel laten staan!!!
      dockerfile_inline: |
        FROM php:8.4-apache
        RUN docker-php-ext-install pdo pdo_mysql
    restart: always
    ports:
      - "http://localhost:8081:80"
      - "8081:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    # Bart beun oplossing voor MAC OS
    # platform: linux/x86_64
    image: mysql:lts
    container_name: airlinermysql_db
    restart: always
    environment:
    # de HOSTNAME is gelijk aan de servicenaam: "db" 
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    # ports blijven default  

  phpmyadmin:
    image: phpmyadmin
    container_name: phpairliner
    restart: always
    ports:

      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
